In [24]:
import numpy as np

In [23]:

w = [[0.2, 0.8],
     [0.6, 0.4],
     [0.5, 0.7],
     [0.9, 0.3]
    ]

w = [[0.2, 0.6, 0.5,0.9], [0.8, 0.4, 0.7, 0.3]]
w = np.array(w)
w

array([[0.2, 0.6, 0.5, 0.9],
       [0.8, 0.4, 0.7, 0.3]])

In [82]:
x = [[1,1,0,0],
     [0,0,0,1],
     [1,0,0,0],
     [0,0,1,1]]

x = np.array(x)

x

array([[1, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 1]])

In [86]:
def index_best_best_fit(x, w, p=2):    
    distances = np.zeros((w.shape[0]))
    
    for i in range(len(w)):
        distances[i] = np.linalg.norm(x - w[i], ord=2)**2
    
    return np.argmin(distances)


index_best_best_fit(x[0], w)

1

In [95]:
for i in range(len(x)):
    print(x[i], index_best_best_fit(x[i], w)+1)

[1 1 0 0] 2
[0 0 0 1] 1
[1 0 0 0] 2
[0 0 1 1] 1


In [107]:
w = [[0.2, 0.6, 0.5,0.9], [0.8, 0.4, 0.7, 0.3]]
w = np.array(w)


def adjust(x, w, alpha):
    
    for k in range(len(x)):
        i = index_best_best_fit(x[k], w)
        w[i] = w[i] + alpha*(x[k] - w[i])
        
    #return w 

alpha = 0.6
adjust(x, w, alpha)

w.T


array([[0.032, 0.968],
       [0.096, 0.304],
       [0.68 , 0.112],
       [0.984, 0.048]])

In [116]:
def loop(x, w, alpha, n):    
    for _ in range(n):
        adjust(x, w, alpha)
        alpha = alpha/2
        
loop(x, w, 0.6, 100)        

w.T

array([[4.63421213e-14, 1.00000000e+00],
       [1.39026364e-13, 4.13935848e-01],
       [5.86064152e-01, 1.62197425e-13],
       [1.00000000e+00, 6.95131820e-14]])

In [118]:

for i in range(4):
    print(x[i], index_best_best_fit(x[i], w)+1)



[1 1 0 0] 2
[0 0 0 1] 1
[1 0 0 0] 2
[0 0 1 1] 1
