

https://medium.com/@navdeepsingh_2336/self-organizing-maps-for-machine-learning-algorithms-ad256a395fc5

In [1]:
import numpy as np
from sklearn.datasets import fetch_olivetti_faces

In [3]:
faces = fetch_olivetti_faces(shuffle=True)

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to /root/scikit_learn_data


In [5]:
dir(faces)

['DESCR', 'data', 'images', 'target']

In [10]:
print(faces['DESCR'])

.. _covtype_dataset:

Forest covertypes
-----------------

The samples in this dataset correspond to 30×30m patches of forest in the US,
collected for the task of predicting each patch's cover type,
i.e. the dominant species of tree.
There are seven covertypes, making this a multiclass classification problem.
Each sample has 54 features, described on the
`dataset's homepage <http://archive.ics.uci.edu/ml/datasets/Covertype>`__.
Some of the features are boolean indicators,
while others are discrete or continuous measurements.

**Data Set Characteristics:**

    =================   ============
    Classes                        7
    Samples total             581012
    Dimensionality                54
    Features                     int
    =================   ============

:func:`sklearn.datasets.fetch_covtype` will load the covertype dataset;
it returns a dictionary-like object
with the feature matrix in the ``data`` member
and the target values in ``target``.
The dataset will be do

In [4]:
faces['data']

array([[0.6694215 , 0.6363636 , 0.6487603 , ..., 0.08677686, 0.08264463,
        0.07438017],
       [0.76859504, 0.75619835, 0.74380165, ..., 0.48347107, 0.6280992 ,
        0.6528926 ],
       [0.37190083, 0.34710744, 0.3677686 , ..., 0.7066116 , 0.6818182 ,
        0.5495868 ],
       ...,
       [0.55785125, 0.60330576, 0.6570248 , ..., 0.17768595, 0.20661157,
        0.19421488],
       [0.5206612 , 0.5206612 , 0.53305787, ..., 0.46694216, 0.43801653,
        0.43801653],
       [0.3966942 , 0.3677686 , 0.3429752 , ..., 0.37190083, 0.26859504,
        0.29752067]], dtype=float32)

In [14]:
Xcomplete = faces['data'].astype(np.float64) / np.max(faces['data'])
X = Xcomplete[0:100]
X

array([[0.66942149, 0.63636363, 0.64876032, ..., 0.08677686, 0.08264463,
        0.07438017],
       [0.76859504, 0.75619835, 0.74380165, ..., 0.48347107, 0.6280992 ,
        0.65289259],
       [0.37190083, 0.34710744, 0.36776859, ..., 0.70661157, 0.68181819,
        0.54958677],
       ...,
       [0.54545456, 0.61157024, 0.6404959 , ..., 0.17355372, 0.17355372,
        0.18181819],
       [0.66115701, 0.74793386, 0.77685952, ..., 0.08677686, 0.10743801,
        0.12809917],
       [0.21900827, 0.28099173, 0.53719008, ..., 0.20247933, 0.17768595,
        0.22727273]])

In [12]:
np.random.shuffle(Xcomplete)

In [15]:
nb_iterations = 5000
nb_startup_iterations = 500
pattern_length = 64 * 64
pattern_width = pattern_height = 64
eta0 = 1.0
sigma0 = 3.0
tau = 100.0
matrix_side = 5

In [21]:
W = np.random.normal(0, 0.1, size=(matrix_side, matrix_side, pattern_length))
W

array([[[ 1.76323776e-02,  9.88162486e-02,  1.48479632e-01, ...,
         -1.51687007e-01,  6.82103724e-03, -1.23653738e-01],
        [ 1.16187409e-01,  1.85912050e-01,  2.14770177e-02, ...,
          4.80493726e-02, -1.19956780e-01,  1.12151500e-01],
        [ 2.06925984e-02, -5.88761304e-02,  1.49958799e-01, ...,
          2.79657339e-02,  1.08726901e-01,  7.70738747e-02],
        [ 6.72930575e-02, -1.30258933e-01, -1.18947384e-01, ...,
          1.23582907e-01,  1.45621271e-02, -2.95334086e-01],
        [ 1.04570792e-01, -1.14285669e-01,  6.61160978e-02, ...,
          7.12144578e-02,  4.01661345e-03,  6.89424410e-02]],

       [[ 5.34264881e-02,  6.20601691e-02, -1.61855395e-01, ...,
         -1.67300958e-01, -2.10178545e-02, -6.12285930e-02],
        [ 1.27875914e-01, -7.24014782e-03, -3.10392172e-02, ...,
          2.26633836e-02, -1.62397010e-01,  1.93769130e-01],
        [ 1.60572668e-01, -1.02159911e-01,  1.05777644e-01, ...,
          1.59230343e-01, -8.58322142e-03, -1.02768

In [22]:
def winning_unit(xt):
    distances = np.linalg.norm(W - xt, ord=2, axis=2)
    max_activation_unit = np.argmax(distances)
    return int(np.floor(max_activation_unit / matrix_side)), max_activation_unit % matrix_side

In [25]:
def eta(t):
    return eta0 * np.exp(-float(t) / tau)

def sigma(t):
    return float(sigma0) * np.exp(-float(t) / tau)

In [26]:
precomputed_distances = np.zeros((matrix_side, matrix_side, matrix_side, matrix_side))
precomputed_distances

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0.,

In [27]:
for i in range(matrix_side):
    for j in range(matrix_side):
        for k in range(matrix_side):
            for t in range(matrix_side):
                precomputed_distances[i, j, k, t] = \
                    np.power(float(i) - float(k), 2) + np.power(float(j) - float(t), 2)
                
def distance_matrix(xt, yt, sigmat):
    dm = precomputed_distances[xt, yt, :, :]
    de = 2.0 * np.power(sigmat, 2)
    return np.exp(-dm / de)

In [28]:
sequence = np.arange(0, X.shape[0])
t = 0
for e in range(nb_iterations):
    np.random.shuffle(sequence)
    t += 1
    if e < nb_startup_iterations:
        etat = eta(t)
        sigmat = sigma(t)
    else:
        etat = 0.2
        sigmat = 1.0
    for n in sequence:
        x_sample = X[n]

        xw, yw = winning_unit(x_sample)
        dm = distance_matrix(xw, yw, sigmat)

        dW = etat * np.expand_dims(dm, axis=2) * (x_sample - W)
        W += dW
        W /= np.linalg.norm(W, axis=2).reshape((matrix_side, matrix_side, 1))

In [29]:
W

array([[[0.01023707, 0.01280016, 0.0151902 , ..., 0.00946711,
         0.00920349, 0.01049012],
        [0.01061538, 0.0129951 , 0.01514953, ..., 0.00875883,
         0.00870491, 0.0096878 ],
        [0.00984353, 0.01163278, 0.01330387, ..., 0.00654007,
         0.00703242, 0.00694008],
        [0.00747403, 0.00937387, 0.0112162 , ..., 0.00593867,
         0.00685256, 0.00644169],
        [0.00688956, 0.00886626, 0.01077015, ..., 0.00589032,
         0.00694579, 0.00650182]],

       [[0.01064968, 0.01312565, 0.01540144, ..., 0.00919976,
         0.00906318, 0.01026412],
        [0.01118569, 0.01333905, 0.01544755, ..., 0.00844777,
         0.00850654, 0.00942631],
        [0.01048889, 0.01207915, 0.01379092, ..., 0.00690643,
         0.00722886, 0.00728468],
        [0.00813199, 0.00990919, 0.01171524, ..., 0.00608264,
         0.00678689, 0.0064475 ],
        [0.00746253, 0.00935337, 0.01120073, ..., 0.0059507 ,
         0.00684946, 0.00644152]],

       [[0.01219472, 0.01378708, 0.0